apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ElMed05/gitops-recipe-app.git # <<-- ÄNDERN
    targetRevision: main
    path: charts/recipe-api
    helm:
      valueFiles:
        - values.yaml  # Pfad zum Helm-Werten
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
