apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dein-user/gitops-recipe-app.git'  # ← Anpassen!
    targetRevision: HEAD
    path: apps/recipe-api
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
